miles_driven= input ("How many miles have been driven? ")
miles_driven= float(miles_driven)
gallons_used= input("How many gallons have been used? ")
gallons_used= float(gallons_used)
print (miles_driven*gallons_used)